#!/bin/zsh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCHEME="course-work-ios"
KEEP_ARTIFACTS=0
RUN_REAL_COREML=1
SHUFFLED_LABELS=0
REAL_COREML_REPLAY=0
TEST_IDENTIFIER="course-work-iosTests/CalibrationSmokeHarnessTests/testStage3CalibrationHistoricalReplaySmoke"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --keep-artifacts)
      KEEP_ARTIFACTS=1
      shift
      ;;
    --skip-real-coreml)
      RUN_REAL_COREML=0
      shift
      ;;
    --shuffled-labels)
      SHUFFLED_LABELS=1
      RUN_REAL_COREML=0
      TEST_IDENTIFIER="course-work-iosTests/CalibrationSmokeHarnessTests/testStage3CalibrationShuffledLabelsDoesNotImprove"
      shift
      ;;
    --real-coreml-replay)
      REAL_COREML_REPLAY=1
      TEST_IDENTIFIER="course-work-iosTests/CalibrationSmokeHarnessTests/testStage3CalibrationRealCoreMLReplaySmoke"
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Usage: scripts/run_calibration_smoke.sh [--keep-artifacts] [--skip-real-coreml] [--shuffled-labels] [--real-coreml-replay]" >&2
      exit 2
      ;;
  esac
done

if [[ "$REAL_COREML_REPLAY" -eq 1 && "$SHUFFLED_LABELS" -eq 1 ]]; then
  echo "Usage error: --real-coreml-replay and --shuffled-labels cannot be combined." >&2
  echo "Usage: scripts/run_calibration_smoke.sh [--keep-artifacts] [--skip-real-coreml] [--shuffled-labels] [--real-coreml-replay]" >&2
  exit 2
fi

ARTIFACTS_DIR="$(mktemp -d /private/tmp/calibration-smoke.XXXXXX)"
DERIVED_DATA_PATH="$ARTIFACTS_DIR/DerivedData"
STORE_PATH="$ARTIFACTS_DIR/calibration-smoke.sqlite"
if [[ "$REAL_COREML_REPLAY" -eq 1 ]]; then
  REPORT_PATH="$ARTIFACTS_DIR/calibration-smoke-report-real-coreml.txt"
elif [[ "$SHUFFLED_LABELS" -eq 1 ]]; then
  REPORT_PATH="$ARTIFACTS_DIR/calibration-smoke-report-shuffled.txt"
else
  REPORT_PATH="$ARTIFACTS_DIR/calibration-smoke-report.txt"
fi
BUILD_LOG="$ARTIFACTS_DIR/build.log"
TEST_LOG="$ARTIFACTS_DIR/test.log"
XCTESTRUN_PATH=""

cleanup() {
  if [[ "$KEEP_ARTIFACTS" -eq 0 ]]; then
    rm -rf "$ARTIFACTS_DIR"
  else
    echo "Artifacts preserved at: $ARTIFACTS_DIR"
    echo "DerivedData preserved at: $DERIVED_DATA_PATH"
  fi
}
trap cleanup EXIT

set_plist_variable() {
  local plist_path="$1"
  local key_path="$2"
  local value="$3"

  /usr/libexec/PlistBuddy -c "Add $key_path string $value" "$plist_path" >/dev/null 2>&1 || \
    /usr/libexec/PlistBuddy -c "Set $key_path $value" "$plist_path"
}

inject_smoke_environment() {
  local plist_path="$1"
  local config_index=0
  local target_index=0

  while /usr/libexec/PlistBuddy -c "Print :TestConfigurations:$config_index" "$plist_path" >/dev/null 2>&1; do
    target_index=0
    while /usr/libexec/PlistBuddy -c "Print :TestConfigurations:$config_index:TestTargets:$target_index" "$plist_path" >/dev/null 2>&1; do
      for env_key in EnvironmentVariables TestingEnvironmentVariables; do
        set_plist_variable "$plist_path" ":TestConfigurations:$config_index:TestTargets:$target_index:$env_key:CALIBRATION_SMOKE_STORE_URL" "$STORE_PATH"
        set_plist_variable "$plist_path" ":TestConfigurations:$config_index:TestTargets:$target_index:$env_key:CALIBRATION_SMOKE_REPORT_PATH" "$REPORT_PATH"
        set_plist_variable "$plist_path" ":TestConfigurations:$config_index:TestTargets:$target_index:$env_key:CALIBRATION_SMOKE_RUN_REAL_COREML" "$RUN_REAL_COREML"
      done
      target_index=$((target_index + 1))
    done
    config_index=$((config_index + 1))
  done
}

DESTINATION_ID="$(
  xcodebuild -scheme "$SCHEME" -showdestinations 2>/dev/null |
    sed -n 's/.*platform:iOS Simulator,.*id:\([^,}]*\).*/\1/p' |
    awk '!/placeholder/ { print; exit }'
)"

if [[ -n "$DESTINATION_ID" ]]; then
  DESTINATION="platform=iOS Simulator,id=$DESTINATION_ID"
else
  DESTINATION="platform=iOS Simulator"
  echo "No concrete simulator ID found; falling back to: $DESTINATION"
fi

echo "Stage 3 Calibration Smoke Harness"
echo "scheme: $SCHEME"
echo "destination: $DESTINATION"
echo "test: $TEST_IDENTIFIER"
echo "artifacts: $ARTIFACTS_DIR"
echo ""

echo "Building test bundle..."
set +e
xcodebuild \
  -scheme "$SCHEME" \
  -sdk iphonesimulator \
  -destination 'generic/platform=iOS Simulator' \
  -derivedDataPath "$DERIVED_DATA_PATH" \
  CODE_SIGNING_ALLOWED=NO \
  build-for-testing | tee "$BUILD_LOG"
BUILD_STATUS=${pipestatus[1]}
set -e
if [[ "$BUILD_STATUS" -ne 0 ]]; then
  echo "Build-for-testing failed. See: $BUILD_LOG" >&2
  exit "$BUILD_STATUS"
fi

typeset -a xctestrun_candidates
xctestrun_candidates=("$DERIVED_DATA_PATH"/Build/Products/*.xctestrun(N))
if [[ ${#xctestrun_candidates[@]} -eq 0 ]]; then
  echo "No .xctestrun file was generated by build-for-testing." >&2
  exit 1
fi

XCTESTRUN_PATH="${xctestrun_candidates[1]}"
inject_smoke_environment "$XCTESTRUN_PATH"

echo ""
echo "Running calibration smoke harness..."
if [[ -n "$DESTINATION_ID" ]]; then
  echo "Booting simulator $DESTINATION_ID for test execution..."
  xcrun simctl boot "$DESTINATION_ID" >/dev/null 2>&1 || true
  xcrun simctl bootstatus "$DESTINATION_ID" -b
fi
echo ""
set +e
xcodebuild \
  -xctestrun "$XCTESTRUN_PATH" \
  -destination-timeout 120 \
  -destination "$DESTINATION" \
  -parallel-testing-enabled NO \
  test-without-building \
  -only-testing:"$TEST_IDENTIFIER" | tee "$TEST_LOG"
TEST_STATUS=${pipestatus[1]}
set -e

echo ""
echo "Smoke report"
if [[ -f "$REPORT_PATH" ]]; then
  cat "$REPORT_PATH"
else
  echo "Smoke report was not generated."
fi

if [[ "$TEST_STATUS" -ne 0 ]]; then
  echo ""
  echo "Smoke harness failed. See: $TEST_LOG" >&2
  exit "$TEST_STATUS"
fi

echo ""
echo "Smoke harness completed successfully."
